//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<BBK> BBK { get; set; }
        public virtual DbSet<Librarian> Librarian { get; set; }
        public virtual DbSet<LostPubs> LostPubs { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<RentedPubs> RentedPubs { get; set; }
        public virtual DbSet<YDK> YDK { get; set; }
    }
}
