//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.LostPubs = new HashSet<LostPubs>();
            this.RentedPubs = new HashSet<RentedPubs>();
            this.Authors = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Annotation { get; set; }
        public int PublisherId { get; set; }
        public Nullable<int> BBK_Id { get; set; }
        public Nullable<int> YDK_Id { get; set; }
        public int Year { get; set; }
        public int Pages { get; set; }
        public string ISBN { get; set; }
        public string Record { get; set; }
        public int Left { get; set; }
        public string ImagePath { get; set; }
    
        public virtual BBK BBK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LostPubs> LostPubs { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual YDK YDK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedPubs> RentedPubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
